// AUTO-GENERATED by scripts/scrape-franchises.ts — do not edit manually.
// Run `npx tsx scripts/scrape-franchises.ts` to refresh, or trigger the
// "Scrape Franchise Listings" GitHub Actions workflow.
// Last synced: 2026-06-14T07:22:48.501Z

import type { Franchise } from './franchises'

export const sourcedListings: Franchise[] = [

]
